### ISSUE TITLE
StructDiscriminatedUnionAnalyzer vs. StructuredFormatDisplayAttribute

### ISSUE THREAD

**Issue by Numpsy** [ionide/ionide-analyzers#102]
**Describe the bug**
I was just running a new project through the analyzers, and had thought that I might get a StructDiscriminatedUnionAnalyzer suggestion from a DU that only has empty and string members, but I got nothing.

Looking at my code, the DU in question has a ```StructuredFormatDisplay``` attribute, and removing that causes a ```Consider adding [<Struct>] to Discriminated Union``` suggestion to appear.

I'm not sure if that is intentional or not, but looking at the analyzer code I wonder if the ```StartsWith("Struct"``` at 
https://github.com/ionide/ionide-analyzers/blob/e66e6038d70255ecdcc5d5321853f1a94bc57e48/src/Ionide.Analyzers/Suggestion/StructDiscriminatedUnionAnalyzer.fs#L29 is perhaps matching more things than it should?

**To Reproduce**

Running the analyzer against a DU such as 
```fsharp
type LicenseValidationResult =
    | Valid
    | Invalid of error: string
```

results in a ```Hint IONIDE-012 : Consider adding [<Struct>] to Discriminated Union``` suggestion, but running it against
```fsharp
[<StructuredFormatDisplay("{DisplayText}")>]
type LicenseValidationResult =
    | Valid
    | Invalid of error: string
```
has no hint.

**Environment (please complete the following information):**
 Ionide analyzers version 0.11.0

**Comment by nojaf** [comment]
Thanks for reporting this. Yes, our check could be better I see.
Would you be interested in submitting a PR for this?

**Comment by Numpsy** [comment]
I'll have a look

**Comment by Numpsy** [comment]
This seems ok in the 0.12.0 release, so I'll close it.
