### ISSUE TITLE
Option.get analyzer

### ISSUE THREAD

**Issue by sheridanchris** [ionide/ionide-analyzers#31]
I think an analyzer for `Option.get` that promotes the graceful handling of the `None` case by using functions like `Option.defaultValue` or pattern matching should be added. I'd like to create a PR for this if you believe this is a useful addition.

**Comment by nojaf** [comment]
Hi Chris,

Thank you for this suggestion! We like it and would be happy to receive a PR for this 🥳!
Don't hesitate to ask any technical questions if you have any.

**Comment by dawedawe** [comment]
This sample could be of help for you to get started:
https://github.com/ionide/FSharp.Analyzers.SDK/blob/master/samples/OptionAnalyzer/Library.fs

**Comment by nojaf** [comment]
Yeah, seems reasonable. Are you interested in submitting a PR?

**Comment by nojaf** [comment]
Would probably be nothing more than adding an OR in `if mfv.FullName = "Microsoft.FSharp.Core.Option.get" && args.Length = 1 then`

**Comment by Numpsy** [comment]
I can have a go later if no one else gets to it first

**Comment by dawedawe** [comment]
I think we should have the `Option.Value` analyzer from the SDK sample as well.
